package org.example.audit.model;

public enum AuditAction {
    INCIDENT_CREATED,
    COMMENT_ADDED,
    STATUS_CHANGED,
    DETAILS_UPDATED,
    SEVERITY_CHANGED,
    REASSIGNED,
    ESCALATED,
    DE_ESCALATED,
    NOTIFICATION_REPLAYED
}
